Add: Flag for Multi Correct
coding-blocks/trouble-maker pull request #10
Opened 2018-08-14 17:15 UTC by firefinchdev

fixes #6

2018-08-14 17:16 UTC, firefinchdev commented
@abhishek97 
Pls Review.

2018-08-15 16:53 UTC, abhishek97 requested changes

2018-08-15 16:53 UTC, abhishek97 commented on routes/api/quiz/controller.js
> +          attributes: ['id', 'title', 'positiveWeight', 'negativeWeight', 'multiCorrect']
choice has no attribute: `multiCorrect`

2018-08-15 16:56 UTC, abhishek97 requested changes

2018-08-15 16:56 UTC, abhishek97 commented on routes/api/questions/controller.js
> +      res.sendStatus(400)
please add an appropriate error message as well.

2018-08-15 19:35 UTC, firefinchdev commented
@abhishek97 Done. Pls review.

2018-08-18 09:40 UTC, firefinchdev commented
@abhishek97 
Any updates?

2018-08-18 15:08 UTC, merged